version: "3.5"

services:
    php-fpm-tenis:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - mysql-tenis
        volumes:
            - ../:/application
            - ./php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/infrastructure-overrides.ini
    webserver-tenis:
        image: nginx:alpine
        ports:
            - "8081:80"
        depends_on:
            - php-fpm-tenis
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ../:/application
    mysql-tenis:
        build:
            context: .
            dockerfile: mysql/Dockerfile
        volumes:
            - ./database:/var/lib/mysql
        ports:
            - "3307:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=u267264214_tenis
            - MYSQL_USER=u267264214_user
            - MYSQL_PASSWORD=JDww2Y9vl2FC
